name: Flow
on: push
jobs:
  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flow
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: npm install
      - name: Flow type check
        run: npm run flow
